routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
Route::resource('participant', 'ParticipantController');
Route::get('dataparticipant', 'ParticipantController@dataparticipant');

app/Biodata.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Biodata extends Model
{
    //
}

app/Donation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Donation extends Model
{
    public function participant(){
    	return $this->belongsTo('App\Participant');
    }
}

app/Participant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Participant extends Model
{
    protected $fillable = [
        'nama',
        'username',
        'email'
    ];

    public function donation(){
    	return $this->hasMany('App\Donation');
    }

    public function biodata(){
    	return $this->hasOne('App\Biodata');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ParticipantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Datatables;
use App\Participant;
use App\Repositories\Repository;

class ParticipantController extends Controller
{
    protected $model;

    public function __construct(Participant $participant){
        $this->model = new Repository($participant);
    }

    public function index(){
        
        return view('participant.index');
    }

    public function dataParticipant(){
        $participant = Participant::select(['id','nama','username','email']);
        return Datatables::of($participant)
        ->addColumn('action',function($participant){
            return '<a href="'.route('participant.edit',$participant->id).'" class="btn btn-primary">Edit</a>
            <button class="btn btn-danger btn-delete" data-remote="/participant/' . $participant->id . '">Delete</button>
            '
        ;})
        ->make(true);
        
    }

    public function show(){

    }

    public function create()
    {
        return view('participant.create');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
        'nama'=>'required',
            'username'=>'required',
            'email'=>'required|email']);
        $this->model->create($request->only($this->model->getModel()->fillable));
        // $participant = new Participant([
        //     'nama' => $request->get('nama'),
        //     'username' => $request->get('username'),
        //     'email' => $request->get('email')
        // ]);
        // $participant->save();
        return redirect('/participant')->with('success','Participant has been saved');
    }

    public function edit($id){
        $participants = Participant::find($id);

        return view('participant.edit', compact('participants'));
    }
    public function update(Request $request, $id){
        $request->validate([
            'nama'=>'required',
            'username'=>'required',
            'email'=>'required|email'
        ]);

        $this->model->update($request->only($this->model->getModel()->fillable), $id);

        return redirect('/participant')->with('success','Participant has been updated');
    }
    public function destroy($id){
        $this->model->delete($id);

        return redirect('/participant')->with('success','Participant has been deleted');
    }
    
}

resources/views/index.blade.php
   @extends('layout')

resources/views/participant/create.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Participant
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('participant.store') }}">
          <div class="form-group">
              @csrf
              <label for="nama">Nama:</label>
              <input type="text" class="form-control" name="nama"/>
          </div>
          <div class="form-group">
              <label for="username">Username :</label>
              <input type="text" class="form-control" name="username"/>
          </div>
          <div class="form-group">
              <label for="email">E-mail:</label>
              <input type="email" class="form-control" name="email"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@endsection

resources/views/participant/edit.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('participant.update', $participants->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="nama">Nama:</label>
          <input type="text" class="form-control" name="nama" value="{{ $participants->nama }}" />
        </div>
        <div class="form-group">
          <label for="username">Username :</label>
          <input type="text" class="form-control" name="username" value="{{ $participants->username }}" />
        </div>
        <div class="form-group">
          <label for="email">E-mail:</label>
          <input type="email" class="form-control" name="email" value="{{ $participants->email }}" />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/participant/index.blade.php
@extends('layout')

@section('content')

        <link  href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  <a href='participant/create' class="btn btn-default">Create</a> 
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif
  <table class="table table-bordered table-striped" id="table">
    <thead>
        <tr>
          <th>ID</th>
          <th>Nama</th>
          <th>Username</th>
          <th>E-mail</th>
          <th colspan="2">Action</th>
        </tr>
    </thead>
   
  </table>
   <script>
         $(function() {
               $('#table').DataTable({
               processing: true,
               ajax: '{{ url('dataparticipant') }}',
               columns: [
                        { data: 'id', name: 'id' },
                        { data: 'nama', name: 'nama' },
                        { data: 'username', name: 'username' },
                        { data: 'email', name: 'email' },
                        {data: 'action', name: 'action', orderable: false, searchable: false}
                     ]
            });
         });
         $('#table').on('click', '.btn-delete[data-remote]', function () {
     
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var url = $(this).data('remote');
        $.ajax({
            url: url,
            type: 'DELETE',
            dataType: 'json',
            data: {method: '_DELETE', submit: true}
        }).always(function (data) {
            $('#table').DataTable().draw(true);
            window.location.reload();
        });
    });
         </script>
<div>
@endsection